using Microsoft.Xna.Framework;
using Rossi_PAC_MAN_Midterm.Objects;
using Microsoft.Xna.Framework.Graphics;
using Rossi_PAC_MAN_Midterm.Objects.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Rossi_PAC_MAN_Midterm.Environment
{
    /*
     *   -------NOT BEING USED PRESET TILES, KEPT TO COPY AND PASTE--------
     *   -------------------floor tiles = walkable-------------------------
     *   new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect);
     *   new Tile(TileType.Floor, Globals.tileMapImage, floor2Rect);
     *   new Tile(TileType.Floor, Globals.tileMapImage, floor3Rect);
     *   new Tile(TileType.Floor, Globals.tileMapImage, floor4Rect);
     *   -------------------wall tiles = !walkable-------------------------
     *   new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect);
     *   new Tile(TileType.Wall, Globals.tileMapImage, wall2Rect);
     *   -----powerup floor = Walkable and has item to eat "ghosts" on them------
     *   new Tile(TileType.Floor, Globals.tileMapImage, cornerRect);
     *   ------------------tube/teleport tiles--------------------------
     *   new Tile(TileType.Floor, Globals.tileMapImage, tube1Rect);
     *   new Tile(TileType.Floor, Globals.tileMapImage, tube2Rect);
    */

    public static class TileMap
    {
        public static int tileSize = 16;
        public static Rectangle floor1Rect = new Rectangle(9 * tileSize, 0 * tileSize, tileSize, tileSize);   //light spaced cobble
        public static Rectangle floor2Rect = new Rectangle(10 * tileSize, 0 * tileSize, tileSize, tileSize);  //light heavy cobble
        public static Rectangle floor3Rect = new Rectangle(9 * tileSize, 1 * tileSize, tileSize, tileSize);   //dark light cobble
        public static Rectangle floor4Rect = new Rectangle(10 * tileSize, 1 * tileSize, tileSize, tileSize);  //dark heavy cobble
        public static Rectangle wall1Rect = new Rectangle(1 * tileSize, 4 * tileSize, tileSize, tileSize);    //dirty dark brick wall
        public static Rectangle wall2Rect = new Rectangle(2 * tileSize, 4 * tileSize, tileSize, tileSize);    //dirty cracked dark brick wall
        public static Rectangle cornerRect = new Rectangle(5 * tileSize, 1 * tileSize, tileSize, tileSize);   //Large Heavy cobble
        public static Rectangle tube1Rect = new Rectangle(1 * tileSize, 11 * tileSize, tileSize, tileSize);   //red gem floor "teleport"
        public static Rectangle tube2Rect = new Rectangle(2 * tileSize, 11 * tileSize, tileSize, tileSize);   //blue gem floor "teleport"

        public const int MAP_ROWS = 30;
        public const int MAP_COLS = 25;
        public const int totalSize = MAP_ROWS * MAP_COLS;

        public static Tile[,] map;
        //floor tiles = walkable

        public static void GenerateMap()
        {
            map = new Tile[MAP_ROWS, MAP_COLS]
            {
                {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Floor, Globals.tileMapImage, tube1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, tube1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Floor, Globals.tileMapImage, tube1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, tube1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Floor, Globals.tileMapImage, floor1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               },
               {
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect),
                    new Tile(TileType.Wall, Globals.tileMapImage, wall1Rect)
               }
            };         
        }
    }
}
